#!/bin/bash


# SCRIPT
# ------------------------------------------

APPLICATION_PATH="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && cd ${DEPLOY_SOURCE_DIR} && pwd )"
cd "$APPLICATION_PATH"

# echo ${BASH_SOURCE[0]} > 1.log
# Git deploy


unset GIT_DIR
git fetch origin
git reset --hard origin/master


# Other post-deploy changes
../scripts/run-deploy -a template
# find . -type d -exec chmod 755 {} \;
# find . -type f -exec chmod 644 {} \;
